### ISSUE TITLE
dataSetMetasetSearch()的query只有title欄位支持關鍵字查詢

### ISSUE THREAD

**Issue by will121** [TaipeiRHackers/DataTaipei#12]
我想這是API的設計，不是我們的程式issue，提供出來為文件參考 
例如: q <- "orgId:379530000H title:停車 organizationContactName:王美玲" 可搜出資料
但把姓名少一字就查不到，如 q <- "orgId:379530000H title:停車 organizationContactName:王美"

**Comment by wush978** [comment]
除非我們建立local metadata database，否則只能依賴http://data.taipei的功能了。
