### ISSUE TITLE
resourceAquire() 撈出結果後有warning messages

### ISSUE THREAD

**Issue by will121** [TaipeiRHackers/DataTaipei#14]
以YouBike臺北市公共自行車即時資訊的rid (rid <- "ddb80380-f1b3-4f8e-8016-7ed9cba571d5") 去執行resourceAquire() 可撈出結果，但有下列warning messages, 看似座標欄位的判斷有些警示 

Warning messages:
1: In data.table::fread(temp) :
  Bumped column 14 to type character on data row 37, field contains '121.529166 '. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses the first 5 rows, the middle 5 rows and the last 5 rows, so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.
2: In data.table::fread(temp) :
  Bumped column 13 to type character on data row 45, field contains '25.01476  '. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses the first 5 rows, the middle 5 rows and the last 5 rows, so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.
3: In data.table::fread(temp) :
  Some columns have been read as type 'integer64' but package bit64 isn't loaded. Those columns will display as strange looking floating point data. There is no need to reload the data. Just require(bit64) to obtain the integer64 print method and print the data again.

**Comment by wush978** [comment]
這是由data.table自動判斷資料形態時產生的警告訊息。

我建議利用這個警告訊息讓使用者清楚資料形態的轉換

**Comment by will121** [comment]
could use suppressWarnings() to turn off the warning message if needed

**Comment by will121** [comment]
suppressWarnings() 已由 resourceParse() 移除，讓錯誤訊息可讓User看到。
