### ISSUE TITLE
DataTaipei package installation warning message

### ISSUE THREAD

**Issue by will121** [TaipeiRHackers/DataTaipei#23]
I use a new computer to install DataTaipei package and come out warning message that I have to install these 8 packages first : ‘httr’,‘XML’,‘RJSONIO’,‘plyr’,‘Rcpp’,‘chron’,‘reshape2’,‘data.table’.  after install these 8 packages , the process of DataTaipei package installation has done successfully.

Should we add some hints in installation guide of above situation to remind to install these 8 packages before DataTaipei installation?

**Comment by wush978** [comment]
Yes! I'll do.
