### ISSUE TITLE
當500時，更改錯誤訊息，並讓使用者選擇是否發信至台北市資訊局

### ISSUE THREAD

**Issue by wush978** [TaipeiRHackers/DataTaipei#28]
有實作上的問題歡迎討論。

**Comment by will121** [comment]
連線失敗會顯示錯誤訊息及發email給北市府(目前先暫發給自己)的功能已改好、commit、push(到自己的repository)完成，是否發出pull requests ?

**Comment by will121** [comment]
新增使用package "mailR"以發送email，會需要把自加到一開始安裝套件的清單中。

**Comment by wush978** [comment]
請發PR，我們在那邊討論一下

**Comment by will121** [comment]
已發PR

**Comment by will121** [comment]
已更改 warning 訊息、判斷是否有mailR套件、是否發送"錯誤連線"通知函給北市府的選擇功能，訊問者須自己輸入gmail的account name 與 password......皆已commit與push，等待pull requist.

**Comment by wush978** [comment]
經過考慮之後，我和 @will121 決定不做「自動寄信的功能」
