### ISSUE TITLE
完成以下三個基礎函數

### ISSUE THREAD

**Issue by wush978** [TaipeiRHackers/DataTaipei#4]
- dataTaipei_GET
- dataTaipei_check
- dataTaipei_parse

**Comment by will121** [comment]
我先做好查詢資料集的核心函數，先commit上去可以嗎，用英文如youBike去查可以，但用中文去查還不行，還在try

**Comment by wush978** [comment]
中文有別的問題，先不急。

如果要commit的話，約個時間我教你們一招github work flow，這樣才不會一天到晚要merge

**Comment by will121** [comment]
好，所以我先不commit ?

**Comment by wush978** [comment]
先放著，等我連線示範的時候再操作即可 :)

**Comment by will121** [comment]
在連線示範前，我先簡單說明三個基礎函數完成的內容與問題:
1.GET : 參數2查詢 title ，若未輸入可查出全部(最多到1000筆，且耗時8分鐘長)，目前問題是參數2可設英數字，但中文會查不出結果
2.check : 沒修改，也沒特別問題
3.parse : 把查詢結果先存成 data.frame (指定兩個欄位) 再把 data.frame 存成csv檔，目前問題是若要把各層的欄位不指定全部放入 data.frame 中還不會寫
謝謝
