### ISSUE TITLE
請教

### ISSUE THREAD

**Issue by HoneJay** [TaipeiRHackers/DataTaipei#48]
你好

照著範例練習   但是...
請問這是甚麼情況呢

> suppressWarnings(df <- resourceAquire(rid$resourceId[1]))
> Error in dataTaipeiCheck(response) : 
> Taipei City Government Open Data Plateform replys the system can't deliver service temporarily.
> Please contact services@mail.taipei.gov.tw if you need further support.
> The accessed url is: http://data.taipei/opendata/datalist/apiAccess?scope=resourceAquire&offset=0&rid=9c6a96d6-353c-41c0-84cc-d181988304f2&format=csv

HJ

**Comment by wush978** [comment]
不好意思，這是台北市政府資訊局那邊的問題。我明天打電話去請教看看。

**Comment by wush978** [comment]
目前台北市政府已經將交通相關資料： http://taipeicity.github.io/traffic_realtime/ 的取得方式做改變，但是在API上沒有做更動。

之後要建立一個例外表了...

**Comment by HoneJay** [comment]
謝謝資訊

所以是因為他的API沒有跟著調整嗎

他們現在都有壓縮  我們沒法先解壓  再讀資料嗎

HJ

2016-03-28 12:08 GMT+08:00 Wush Wu notifications@github.com:

> 目前台北市政府已經將交通相關資料： http://taipeicity.github.io/traffic_realtime/
> 的取得方式做改變，但是在API上沒有做更動。
> 
> 之後要建立一個例外表了...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/TaipeiRHackers/DataTaipei/issues/48#issuecomment-202224080

## 

Hone-Jay Chu, Ph.D., Assistant Professor
Department of Geomatics
National Cheng Kung University
No.1, University Road, Tainan City 701, Taiwan

**Comment by wush978** [comment]
因為我是依照 http://data.taipei/opendata/developer 上的指南進行開發，

而目前在access這類資料時，是直接給500

已經去信希望他們能更新API，讓我可以直接redirect到新的網址。

如果你想要爬這些資料，我建議直接`download.file`後直接用相關套件讀取即可。
